"""rename department

Revision ID: 5d5cd3ceff11
Revises: e0d73f30561a
Create Date: 2024-07-03 01:10:41.401400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5cd3ceff11'
down_revision = 'e0d73f30561a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
   
